config/routes.rb
Rails.application.routes.draw do
	devise_for :usuarios, controllers: { sessions: 'usuarios/sessions' }
  
  controller :usuarios do
    get '/usuarios/listar_para_autocomplete' => :listar_para_autocomplete
  end
  resources :usuarios

  controller :tarefas do 
    get "tarefas/nova_tarefa" => :nova_tarefa, as: :nova_tarefa
    get "tarefas/cancelar_tarefa/:id" => :cancelar_tarefa, as: :cancelar_tarefa
    get "tarefas/concluir_tarefa/:id" => :concluir_tarefa, as: :concluir_tarefa
  end
  resources :tarefas

  controller :equipes do 
    get "equipes/nova_equipe" => :nova_equipe, as: :nova_equipe
    post "equipes/adicionar_membro" => :adicionar_membro, as: :adicionar_membro
    post "equipes/remover_membro" => :remover_membro, as: :remover_membro
  end
  resources :equipes

  root to: 'tarefas#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
  enum status: [:a_fazer, :em_andamento, :concluida, :cancelada]

  STATUS_ORDERS = [0, 1, 2]

  scope :order_by_status, -> {
    order_by = ['CASE']
    STATUS_ORDERS.each_with_index do |status, index|
      order_by << "WHEN status=#{status} THEN #{index}"
    end
    order_by << 'END'
    order(order_by.join(' '))
  }

  validates :inicio, :nome, presence: true
  validates :motivo_cancelamento, :termino, presence: true, if: :cancelada?
  validates :termino, presence: true, if: :concluida?
  validate :termino_tarefa

  belongs_to :usuario

  def termino_tarefa
    unless self.termino.blank?
      if self.termino.to_date < self.inicio.to_date
        errors.add(:base, "Término da tarefa deve ser posterior ao Início.")
      end
    end
  end

  def status_to_s
    return "" if self.status.blank?
    return Tarefa.human_attribute_name("statuses.#{status}")
  end

  def termino_to_s
    return "Tarefa em andamento" if self.termino.blank?
    return self.termino.strftime("%d/%m/%Y às %H:%M")
  end

  def finalizada?
    return true if self.concluida? or self.cancelada?
    return false
  end

  def inicio_to_s
    return self.inicio.strftime("%d/%m/%Y às %H:%M") unless self.inicio.blank?
  end
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController

  before_action :authenticate_usuario!
  before_action :set_tarefa, only: [:cancelar_tarefa, :show, :update, :concluir_tarefa]


  def index
    @tarefas = Tarefa.where(usuario_id: current_usuario.id).order_by_status.order('tarefas.inicio ASC')
  end

  def new
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def create
    parameters = tarefa_params
    parameters[:usuario_id] = current_usuario.id
    @tarefa = Tarefa.create(parameters)
    if @tarefa.errors.any?
      flash[:warning] = @tarefa.errors.full_messages.map(&:inspect).join(', ')
    else
      flash[:success] = "Tarefa criada com sucesso!"
    end
    redirect_to tarefas_path
  end

  def update
    if @tarefa.update_attributes(tarefa_params)
      flash[:success] = "Tarefa salva!"
    else
      flash[:warning] = @tarefa.errors.full_messages.map(&:inspect).join(', ')
    end
    redirect_to tarefas_path
  end

  def nova_tarefa
    respond_to do |format|
      format.html
      format.js
    end
  end

  def cancelar_tarefa
    respond_to do |format|
      format.html
      format.js
    end
  end

  def concluir_tarefa
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
    def tarefa_params 
      params.require(:tarefa).permit(:nome, :inicio, :termino, :motivo_cancelamento, :status)
    end

    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/tarefas/_cancelar_tarefa_modal.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Cancelar <%= tarefa.nome %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <p><b>Início:</b> <%= tarefa.inicio_to_s %></p>
  <%= form_for tarefa, url: {action: "update"} do |f| %>
    <%= f.hidden_field :status, value: "cancelada" %>
    <div class="form-group">
      <%= f.label :termino %><br />
      <%= f.datetime_field :termino, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :motivo_cancelamento %><br />
      <%= f.text_area :motivo_cancelamento, class: "form-control" %>
    </div>

    <%= f.submit "Finalizar", class: "btn btn-primary btn-block" %>

  <% end %>
</div>

app/views/tarefas/_concluir_tarefa_modal.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Finalizar <%= tarefa.nome %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <p><b>Início:</b> <%= tarefa.inicio_to_s %></p>
  <%= form_for tarefa, url: {action: "update"} do |f| %>
    <%= f.hidden_field :status, value: "concluida" %>
    <div class="form-group">
      <%= f.label :termino %><br />
      <%= f.datetime_field :termino, class: "form-control" %>
    </div>

    <%= f.submit "Finalizar", class: "btn btn-primary btn-block" %>

  <% end %>
</div>

app/views/tarefas/_list.html.erb
<table class="table table-striped table-bordered mb-5">
  <thead class="table-dark text-center">
    <tr>
      <th scope="col"><%= I18n.t('activerecord.attributes.tarefa.tarefas') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.tarefa.inicio') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.tarefa.termino') %></th>
      <th scope="col"><%= I18n.t('activerecord.attributes.tarefa.status') %></th>
      <% if tarefas_proprias %>
        <th scope="col"><%= I18n.t('activerecord.attributes.tarefa.acoes') %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% tarefas.each do |tarefa| %>
      <tr class="text-center">  
        <td><%= link_to tarefa.nome, tarefa_path(tarefa), remote: true %></td>
        <td><%= tarefa.inicio_to_s %></td>
        <td><%= tarefa.termino_to_s unless tarefa.termino.blank? %></td>
        <td><%= tarefa.status_to_s %></td>
        <% if tarefas_proprias %>
          <td>
            <% unless tarefa.finalizada? %>
              <%= link_to cancelar_tarefa_path(tarefa), remote: true, :title => 'Cancelar' do %>
                <%= render "templates/svg/red_cross" %> 
              <% end %>
              <%= link_to concluir_tarefa_path(tarefa), remote: true, :title => 'Concluir' do %>
                <%= render "templates/svg/blue_check" %>
              <% end %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tarefas/_nova_tarefa.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Nova Tarefa</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <%= form_for(:tarefa, url: { action: "create" }) do |f| %>
    <%= f.hidden_field :status, value: "em_andamento" %>
    <div class="form-group">
      <%= f.label :nome %><br />
      <%= f.text_field :nome, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :inicio %><br />
      <%= f.datetime_field :inicio, class: "form-control" %>
    </div>

    <%= f.submit "Criar", name:"submit" ,class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/tarefas/_tarefa_modal.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%= tarefa.nome %> - <%= tarefa.status_to_s %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <p><b>Início:</b> <%= tarefa.inicio_to_s %></p>
  <p><b>Término:</b> <%= tarefa.termino_to_s %></p>
  <% if tarefa.cancelada? %>
    <p><b>Motivo do Cancelamento:</b></p>
    <p><%= tarefa.motivo_cancelamento %></p>
  <% end %>
</div>
    

app/views/tarefas/cancelar_tarefa.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'cancelar_tarefa_modal', tarefa: @tarefa %>");
$("#modal-window").modal('show');

app/views/tarefas/concluir_tarefa.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'concluir_tarefa_modal', tarefa: @tarefa %>");
$("#modal-window").modal('show');

app/views/tarefas/index.html.erb
<div class="container">
  <%= render "templates/top_menu" %>

  <h2>Minhas Tarefas</h2>
  <%= render "list", tarefas: @tarefas, tarefas_proprias: true %>

  <% if current_usuario.gestor? %>
    <hr class="m-5">
    <h2 class="mb-3">Minhas Equipes</h2>
    <% current_usuario.equipes.each_with_index do |equipe, index| %>
      <h4 class="mb-3">
        <%= link_to equipe.nome, equipe_path(equipe), remote: true %>
      </h4> 
      <% equipe.usuarios.each do |usuario| %>
        <% unless usuario == current_usuario %>
          <h6>
            <%= usuario.nome %>
          </h6> 
          <%= render "list", tarefas: usuario.tarefas, tarefas_proprias: false %>
        <% end %>
      <% end %>
      <% unless index == (current_usuario.equipes.count - 1) %>
        <hr class="m-5">
      <% end %>
    <% end %>
  <% end %>

  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
    
</div>

app/views/tarefas/nova_tarefa.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'nova_tarefa') %>");
$("#modal-window").modal();

app/views/tarefas/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'tarefa_modal', tarefa: @tarefa %>");
$("#modal-window").modal('show');