config/routes.rb
Rails.application.routes.draw do
	devise_for :usuarios, controllers: { sessions: 'usuarios/sessions' }
  
  controller :usuarios do
    get '/usuarios/listar_para_autocomplete' => :listar_para_autocomplete
  end
  resources :usuarios

  controller :tarefas do 
    get "tarefas/nova_tarefa" => :nova_tarefa, as: :nova_tarefa
    get "tarefas/cancelar_tarefa/:id" => :cancelar_tarefa, as: :cancelar_tarefa
    get "tarefas/concluir_tarefa/:id" => :concluir_tarefa, as: :concluir_tarefa
  end
  resources :tarefas

  controller :equipes do 
    get "equipes/nova_equipe" => :nova_equipe, as: :nova_equipe
    post "equipes/adicionar_membro" => :adicionar_membro, as: :adicionar_membro
    post "equipes/remover_membro" => :remover_membro, as: :remover_membro
  end
  resources :equipes

  root to: 'tarefas#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/templates/_alert.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> text-center"><%= value %></div>
<% end %>

<script type="text/javascript">
  // Remove mensagem alert depois de 4 segundos
  <% if defined?(keep).nil? %>
    setTimeout(function(){hideSystemNotice()}, 4000);
  <% end %>

  function hideSystemNotice() {
    $('.alert').slideUp('slow', function() {
      $('.alert').hide();
    });
  }
</script>

app/views/templates/_autocomplete_remote_tag.html.erb
<script type="text/javascript">
  $(function() {
    $('<%= dom_element %>').autocomplete({
        minLength: 3,
        source: function(request, response) {
          $.ajax({
            url: '<%= source_path %>',
            dataType: 'json',
            data: {
              term: request.term,
              <% if defined? additional_params %>
                <%= additional_params.collect{|key, value| "#{key.to_s}: $(\"##{value.to_s}\").val()".html_safe}.join(',').html_safe %>
              <% end %>
            },
            beforeSend: function() {
              $('<%= dom_element %>').addClass('loader');
            },
            success: function(data) {
              $('<%= dom_element %>').removeClass('loader');
              response($.map(data, function(item) {
                return {
                  label: item.label,
                  value: item.value
                }
              }));
            }
          });
        },
        focus: function( event, ui ) {
          $( '<%= dom_element %>' ).val( ui.item.label );
          return false;
        },
        select: function( event, ui ) {
          $( '<%= dom_element %>' ).val( ui.item.label );
          $( '<%= dom_element_id %>' ).val( ui.item.value ).trigger('change');
          return false;
        },
        appendTo: "<%= append_to unless append_to.blank? %>"
      });

    $(document).on('blur', "<%= dom_element %>", function() {
      if($(this).val() == "" ) {
        $('<%= dom_element_id %>').val("").trigger('change');
      }
    });

  });

</script>

app/views/templates/_top_menu.html.erb
<div class="header mb-5 mt-3">
  <h1 class="d-inline">Bem-vindo, <%= current_usuario.nome %></h1>
  <div class="botoes_header d-inline float-right mt-1">
    <%= link_to 'Nova Tarefa', nova_tarefa_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg'}  %>
    <% if current_usuario.gestor? %>
      <%= link_to 'Nova Equipe', nova_equipe_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-secondary btn-lg'}  %>
    <% end %>
    <%= link_to('Logout', destroy_usuario_session_path, method: :delete) %> 
  </div>
</div>